### ISSUE TITLE
Is this the main repo to develop XMP Toolkit SDK

### ISSUE THREAD

**Issue by HuKeping** [adobe/XMP-Toolkit-SDK#14]
Hi @Priyanka-Gupta @pawankishorsingh , 

At present people can only download the source of XMP ToolKit SDK from https://www.adobe.com/devnet/xmp.html . 

I wonder if this git repo would be the main place to develop XMP Toolkit SDK, and is there any plan to introduce release tag?

**Comment by pawankishorsingh** [comment]
Hi @HuKeping 
We have added a release tag in this github repo and going forwards all the developments & successive releases will happen from here only.
Hope it information helps.
Closing this issue. Hope its fine.

**Comment by HuKeping** [comment]
Thanks @pawankishorsingh , it helps a lot.
