### ISSUE TITLE
License no longer BSD

### ISSUE THREAD

**Issue by hfiguiere** [adobe/XMP-Toolkit-SDK#16]
Each license header include the following sentence that wasn't in the previous release.

> If you have received this file from a source other than Adobe, then your use, modification, or distribution of it requires the prior written permission of Adobe.

This mean that redistribution of the source code is restricted, therefor this is no longer BSD 3-clause licensed source code, and other open source package that include that code are no longer allowed to do so.

The README is therefor misleading.

**Comment by hfiguiere** [comment]
This came with #6

**Comment by hfiguiere** [comment]
The license file has been updated in pr #17 to not have this clause like in the previous releases

But it is still in the various file headers which give the impression that the source code can't be redistributed, contrary to the BSD 3-clause

**Comment by tester0077** [comment]
but the link to the license file in the Readme file is broken. 
So where do we find it spelled out authoritatively?

**Comment by arpitapanda05** [comment]
@pawankishorsingh Please check this

**Comment by hfiguiere** [comment]
This isn't part of the just release v2021.1 and this is really disappointing.

**Comment by pawankishorsingh** [comment]
Hi @tester0077 
The "link to the license file in the Readme file" has been fixed now. Please have a look again.

**Comment by pawankishorsingh** [comment]
Hi @hfiguiere 
In May-2021 when you had reported this issue, I had a discussion with Adobe Licensing Team and they instructed me that lets not change the terms in so many header files in existing code because that would be too much of an effort. But, in the new code that we write, we should use the new terms.
Considering that advise, I had not modified "all" instances where old language was used.
But since you explicitly mentioned the names of 6 files in [this PR](https://github.com/adobe/XMP-Toolkit-SDK/pull/6/files) , I specifically made changes in these 6 files.
Hence, as of today, you are not seeing the new license text in "all" the places, but you'll find it well in place in [these 6 files](https://github.com/adobe/XMP-Toolkit-SDK/pull/6/files) because you explicitly asked for those.

So, please don't be disappointed since we appreciate your contribution very much. We are considering your advise very well but we are taking a prudent/middle path.

**Comment by hfiguiere** [comment]
All the headers include :

> If you have received this file from a source other than Adobe,
> then your use, modification, or distribution of it requires the prior
> written permission of Adobe.

**This goes against the BSD 3-clause** because it prohibit redistribution, at least to my understanding as I am not a lawyer. In short **the headers are incompatible with the license it claims it is under**.

As I said in the original report this was added with PR #6. Nothing has changed since June 24 2020.

Previous version of the SDK like release CC 2016.07 didn't include that restriction.

It is not a "detail". This basically prohibit using XMP SDK in any piece of FLOSS software as it wouldn't pass the review of most of the license review in Linux distribution that care about license (Debian, Fedora, etc)
As the maintainer of "exempi" I can't update the base code to the XMP SDK because of this. So I'm stuck with CC 2016.07. 

It was thrilled to see that the XMP SDK was now in a public git repository, but this is clearly a show stopper.

Now you say it is too much of an effort, so if I do the work and submit a PR to remove this clause will you merge it?

**Comment by pawankishorsingh** [comment]
Hi @hfiguiere 
I got your point.
There is another SDK release happening in Auguts-2021. I'll get the language updated in the headers. Please stay tuned for next release.

**Comment by tester0077** [comment]
I have to agree with Hubert; as I received the original code from adobe, I
could use the old code, but will never be able to use any
'improvement/updates from git

**Comment by xsuchy** [comment]
Any progress? It would be awesome if you can publish the commits which fix this issue prior the August's release. So the non-fixed release v2021.1 does not repeat. I will be glad to verify and review these commits.
Without this issue being resolved we cannot include this project in future versions of RHEL/CentOS. :(

**Comment by pawankishorsingh** [comment]
Hi @xsuchy 
Here is the commit having this change- https://github.com/adobe/XMP-Toolkit-SDK/commit/f24b96f
Please verify & tell me if its fine?

**Comment by nforro** [comment]
> Hi @xsuchy
> Here is the commit having this change- [f24b96f](https://github.com/adobe/XMP-Toolkit-SDK/commit/f24b96f)
> Please verify & tell me if its fine?

Yes, this is great, thank you. Can we expect a new release soon?

**Comment by pawankishorsingh** [comment]
Thanks. In coming 2 weeks you can expect new release.
