### ISSUE TITLE
Attempting to load JPEG image using XmpFiles throws exception

### ISSUE THREAD

**Issue by danpetitt** [adobe/XMP-Toolkit-SDK#19]
We are getting an "Out of bounds IFD" error message when attempting to get the XMP using XmpFiles.

![TeamPluto.jpg](https://user-images.githubusercontent.com/1733292/92224549-db027600-ee99-11ea-8880-cdc9a3f484eb.jpg)

**Comment by pawankishorsingh** [comment]
Thanks for reporting this issue.
I'm getting it investigated by XMP engineers in Adobe. We will revert soon.

**Comment by danpetitt** [comment]
To give more info; the problem is due to the `IsOffsetValid` function within `TIFF_FileWriter::ParseMemoryStream`.

The `length` is passed in as 9577 which means we have an `ifdLimit` of 9571 (9577 - 6).

When `tnailOffset` is calculated is it 9575 which is more than the upper limit of 9571.

The image, I believe, is created using Adobe Bridge.

**Comment by danpetitt** [comment]
Hi @pawankishorsingh ... sorry to hassle, is this something being actively worked on/investigated?

**Comment by pawankishorsingh** [comment]
Yes. Our XMP team is actively working on this issue and I'm hoping to provide you a fix soon.

**Comment by danpetitt** [comment]
Sorry @pawankishorsingh, is there any news? Is there anything I can do to help move this along?

**Comment by pawankishorsingh** [comment]
Hi @danpetitt 

Our XMP team has investigated it and we have discussed it internally. We feel that this issue should get fixed at "Adobe Bridge" end since it is the one which is putting wrong value of iNailOffset.
Can you please tell us the steps to recreate this issue in Adobe Bridge? 
Once we know the steps, we'll go ahead and log a bug in Adobe Bridge.

Regards
Pawan

**Comment by danpetitt** [comment]
That's unfortunate as we cannot ask our customer to re-save tens of thousands of images in Adobe Bridge.

As they created the images in the first place, I cannot give you any specific steps and I do not have a licence for it so I cant attempt to create any steps for you. Let me see if I can get hold of a trial.

**Comment by danpetitt** [comment]
Are you sure you cannot just work around it in this library; it seems prudent to do it here rather than rely on an (Adobe) application to fix their issue and expect every image in the world saved by Adobe Bridge to be re-saved with an upgraded version of the product.
