### ISSUE TITLE
Does not build with Xcode 12

### ISSUE THREAD

**Issue by carstengp-hb** [adobe/XMP-Toolkit-SDK#21]
Maybe also older versions of Xcode but 12 is what I'm using and getting this result after executing GenerateXMPToolkitSDK_mac.sh:

Check dependencies
No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=arm64, VALID_ARCHS=arm64 arm64e i386 x86_64, EXCLUDED_ARCHS=(
    arm64,
    arm64e
)).

** BUILD FAILED **

Not really sure why it would assume active arch=arm64 as it is on an Intel Mac running macOS 10.15.6
And admittedly I'm not an expert cmake user

**Comment by arpitapanda05** [comment]
Currently, we are supporting Xcode 10.2. Let us know if you face any issues with it.

**Comment by wihab** [comment]
To add support for arm64, we need to use XCode 12. Why would we not consider adding support?
