### ISSUE TITLE
VS2019 Support

### ISSUE THREAD

**Issue by ChristianRiedl** [adobe/XMP-Toolkit-SDK#25]
Would be great to support Visual Studio 2019.
It is tedious to keep old VS versions because important libraries are not updated.

**Comment by arpitapanda05** [comment]
Thank you for the suggestion. We are looking into it.

**Comment by wihab** [comment]
Any plans to potentially reconsider support for MSVC 2019? This would be very helpful as technologies progress forward.

**Comment by cvmanjesh** [comment]
@arpitapanda05, @ChristianRiedl @wihab does that mean if the code that links to XMP library, uses Visual studio 2019, the XMP library will not work correctly as of today?
