### ISSUE TITLE
Cannot write GPano property into jpeg file on iOS

### ISSUE THREAD

**Issue by lmartin** [adobe/XMP-Toolkit-SDK#31]
I started from SDK code in "samples/source/ModifyingXMP.cpp", I just added this few lines to write [GPano](https://developers.google.com/streetview/spherical-metadata?hl=fr) metadata :
```
// register namespace
string actualPrefix;
SXMPMeta::RegisterNamespace( "http://ns.google.com/photos/1.0/panorama/", "GPano:", &actualPrefix );

// write gpano property
meta.SetProperty("http://ns.google.com/photos/1.0/panorama/", "ProjectionType", "equirectangular", 0);
```

I use this lines to dump meta content :
```
SXMPIterator iter( meta );
string schemaNS,propPath,propVal;
while( iter.Next( &schemaNS, &propPath, &propVal )){
    cout << schemaNS << " " << propPath << " = " << propVal << endl;
}
```

When I dump meta, I have this :
```
http://purl.org/dc/elements/1.1/  = 
http://purl.org/dc/elements/1.1/ dc:creator = 
http://purl.org/dc/elements/1.1/ dc:creator[1] = Author Name
http://purl.org/dc/elements/1.1/ dc:creator[2] = Another Author Name
http://purl.org/dc/elements/1.1/ dc:title = 
http://purl.org/dc/elements/1.1/ dc:title[1] = An English title
http://purl.org/dc/elements/1.1/ dc:title[1]/?xml:lang = x-default
http://purl.org/dc/elements/1.1/ dc:title[2] = An English title
http://purl.org/dc/elements/1.1/ dc:title[2]/?xml:lang = en-US
http://purl.org/dc/elements/1.1/ dc:title[3] = Un titre Francais
http://purl.org/dc/elements/1.1/ dc:title[3]/?xml:lang = fr-FR
http://ns.google.com/photos/1.0/panorama/  = 
http://ns.google.com/photos/1.0/panorama/ GPano:ProjectionType = equirectangular
```
 
So it is ok I see the GPano property when I dump the meta.

But my problem is that I don't retrieve GPano metadata in exported file while I see correctly other XMP properties added by the sample code. I use ApolloOne app or thexifer website or exiftool to check file metadata. Here is the exported file :

![LPVK8002](https://user-images.githubusercontent.com/488436/117257161-ddafd380-ae4b-11eb-878e-ac17b6fc9dd1.jpeg)
 
It looks like GPano property is not exported to file, is it a bug or my misunderstanding?

Note 1 : no problem with same code on Android.

Note 2 : I also tried to just forward metadata by reading XMP from a file that have correct GPano metadata and writing these XMP to a new file, it failed too. I mean I don't retrieve Gpano in the new file while other metadata are present.  

Note 3 : when building iOS SDK, I had to define "XML_POOR_ENTROPY" in "third-party/expat/lib/xmlparse.c"

**Comment by ErinFinnegan** [comment]
So, an XMP fix will be in Illustrator 25.3 and InDesign 16.3... however, I'm not sure if that will solve your issue.

**Comment by lmartin** [comment]
Does this fix apply to Adobe XMP SDK or only to Adobe softwares?

**Comment by maupadhyay** [comment]
From the above description it is not clear whether PutXMP(meta) e.g. [ModifyingXMP.cpp#L276](https://github.com/adobe/XMP-Toolkit-SDK/blob/main/samples/source/ModifyingXMP.cpp#L276) and after that CloseFile() e.g. [ModifyingXMP.cpp#L281](https://github.com/adobe/XMP-Toolkit-SDK/blob/main/samples/source/ModifyingXMP.cpp#L281) API is being called or not to finally write the xmp packet in the asset.
This issue is not reproducible at our end. Can you please try with the latest release and see if you are still facing this issue.
