### ISSUE TITLE
XMP can't be read from png files (iOS)

### ISSUE THREAD

**Issue by ThaiLanKing** [adobe/XMP-Toolkit-SDK#33]
XMP information can be read from jpg and pdf, but  cannot be read from png files。

### Expected Behaviour

read XMP information from jpg、png

### Actual Behaviour

XMP information can be read from jpg and pdf, but  cannot be read from png files。

### Reproduce Scenario (including but not limited to)

test with BlueSquare.png in this project, GetXMP method return no XMP

#### Steps to Reproduce

test with BlueSquare.png in this project, GetXMP method return no XMP

#### Platform and Version

iOS 11.2.6 
Xcode 12.1

**Comment by arpitapanda05** [comment]
Hi @ThaiLanKing we have tried to reproduce the issue at our end and it wasn't reproducible. We were able to read from .png files in iOS. I would suggest you checking with SDK-compatible versions of Xcode & iOS.
