### ISSUE TITLE
Earlier versions of the toolkit are not available: 2016.07

### ISSUE THREAD

**Issue by AlexImagineComm** [adobe/XMP-Toolkit-SDK#36]
Unfortunately I can not download the **2016.07** version. It’s not available any more, after I click this version on https://www.adobe.com/devnet/xmp.html  and get to the EULA page – the zip is not available.
I click: XMP Toolkit SDK CC-2016.07 (ZIP, 38.7 MB) and get on the https://www.adobe.com/devnet/xmp/sdk/eula-cc20168.html
I click: "Agree and download XMP Toolkit SDK CC-2016.7" - no zip is downloaded.
Can I get the **XMP Toolkit SDK CC-2016.7** ?  Our software depends on this library and we wanted to re-compile it for Linux.

**Comment by arpitapanda05** [comment]
Thanks for bringing it to our notice, we'll be looking into it.

**Comment by hfiguiere** [comment]
You can find a verbatim copy in that repository / revision:

https://gitlab.freedesktop.org/libopenraw/exempi/-/commit/6071af09b5e263b63e57b28ab8a78484bc65e3fe

**Comment by pawankishorsingh** [comment]
I was able to download it in usual way:

1. Open https://www.adobe.com/devnet/xmp.html 
2. Click on [XMP Toolkit SDK CC-2016.07 (ZIP, 38.7 MB)](https://www.adobe.com/devnet/xmp/sdk/eula-cc20168.html)
3. A new page opens up i.e. https://www.adobe.com/devnet/xmp/sdk/eula-cc20168.html
4. Click [Agree and download XMP Toolkit SDK CC-2016.7 (ZIP, 38.7 MB)](http://download.macromedia.com/pub/developer/xmp/sdk/XMP-Toolkit-SDK-CC201607.zip)

**Comment by AlexImagineComm** [comment]
Thanks, indeed now it works for IE only,
