### ISSUE TITLE
Request for an update for Apple Silicon arch

### ISSUE THREAD

**Issue by neolib** [adobe/XMP-Toolkit-SDK#37]
I downloaded 2010.1 source code and after some hacking and tuning, I finally successfully built dynamic frameworks from the generated project.

But I have a very weird problem with the static builds.

- Debug build produces two .a files as expected (each more than 50Mb).
- Archive build produces an .xcarchive file with just 300+ BYTES (not Kb).

I believe I am doing something wrong. It's better to leave this for the experts. So please release an update to address this issue.

**Comment by neolib** [comment]
BTW, I have to define XML_POOR_ENTROPY to get the project build. Is this by design?

macOS Big Sur 11.4
Xcode 12.5.1

**Comment by MattTimmons** [comment]
same here. Thanks!

**Comment by amitwaisel** [comment]
@neolib looks like you have to clone `expat 2.1.0` instead of the latest `expat 2.4.4` third-party library.

I have a follow-up question, is there any intention releasing a M1-compiled version of the `PDF_Handler` XMPFiles plugin? What is the expected time for that?

**Comment by maupadhyay** [comment]
[v2022.02](https://github.com/adobe/XMP-Toolkit-SDK/tree/v2022.02) and onwards have Apple silicon support. Universal build of PDF_Handler is available with [v2023.12](https://github.com/adobe/XMP-Toolkit-SDK/tree/v2023.12) at `XMPFilesPlugins/PDF_Handler/macintosh/universal/PDF_Handler.xpi`
