### ISSUE TITLE
Remove "Adobe Confidential" headers

### ISSUE THREAD

**Issue by macdonst** [adobe/XMP-Toolkit-SDK#4]
Some of the files in this repo have "Adobe Confidential" in the headers. This should be removed as it gives folks the impression this project is not licensed under BSD-3-Clause. This may discourage folks from using the project and the open source office has already received one inquiry about the above.

**Comment by pawankishorsingh** [comment]
Hi Simon

I can see these 6 instances where "**_ADOBE CONFIDENTIAL_**" string is left out. This is not any new inclusion as I can see it was there even in our year-2014 and year-2016 SDKs. 
Presently these are present in:
1. source/SafeTypes.h
2. build/shared/SharedConfig_Android.cmake
3. build/ProductConfig.cmake
4. source/SafeStringAPIs.cpp
5. source/SuppressSAL.h
6. source/SafeStringAPIs.h
I used this [search query](https://github.com/adobe/XMP-Toolkit-SDK/search?q=Adobe+Confidential&unscoped_q=Adobe+Confidential) to find these.

I intend to make changes to rectify this. But before I do that I just want to check with you if these are the same set of issues which you wanted to refer to?

Kindly confirm.

Regards
Pawan

**Comment by macdonst** [comment]
@pawankishorsingh yeah, we specifically received a question on the .cpp/.h files but removing it from the .cmake files as well and replacing it with the BSD-Clasue-3 headers would be good.

**Comment by pawankishorsingh** [comment]
"Adobe Confidential" has been removed from the 6 places which I mentioned above. There are few more changes upcoming related to licensing. But we're tracking them from another issue. Hence closing this issue. Hope its fine.
