### ISSUE TITLE
iOS : cannot forward GPS metadata

### ISSUE THREAD

**Issue by lmartin** [adobe/XMP-Toolkit-SDK#48]
I started from SDK code in "samples/source/ModifyingXMP.cpp".
I just extract XMP metadata from my photo source and reinject it in my new photo.
Result is that my new photo has all metadata from my photo source except GPS metadata.

Problem only on iOS, no problem on Android.

**Comment by Priyanka-Gupta** [comment]
Thanks for reporting it. Could you please share the test files with which you are facing the issue.

**Comment by lmartin** [comment]
You can reproduce the issue with any photo with GPS metadata.

**Comment by maupadhyay** [comment]
This issue is not reproducible.
