### ISSUE TITLE
Support M1 (Apple Silicon) for `PDF_Handler` pre-compiled XMPFiles plugin

### ISSUE THREAD

**Issue by amitwaisel** [adobe/XMP-Toolkit-SDK#54]
Is there any intention releasing a M1-compiled version of the `PDF_Handler` XMPFiles plugin? What is the expected time for that?
If not, will you share the source code for `PDF_Handler` so it can be compiled locally?

Thank you

**Comment by Priyanka-Gupta** [comment]
It's already in our plan, we will be releasing M1 compiled version of PDF_Handler in near future.

**Comment by amitwaisel** [comment]
Thank you @Priyanka-Gupta, I didn't find the new version of `PDF_Handler` in `2022.02` release. What is the expected timeline for the release?

**Comment by amitwaisel** [comment]
Hello @Priyanka-Gupta, do you have any update regarding the timeline for releasing the `PDF_Handler` plugin for Apple Silicon?

**Comment by mbel1** [comment]
Hello @Priyanka-Gupta! would it be possible to give any hint on expected timeline for Apple Silicon support for `PDF_Handler`?

**Comment by maupadhyay** [comment]
PDF_Handler universal binary has been released as part of [December 2023 Release](https://github.com/adobe/XMP-Toolkit-SDK/releases/tag/v2023.12) and is available at `XMPFilesPlugins/PDF_Handler/macintosh/universal/PDF_Handler.xpi`
