### ISSUE TITLE
Question: Inserting Localized Text Item Into Struct Field

### ISSUE THREAD

**Issue by jwsinner** [adobe/XMP-Toolkit-SDK#60]
I've searched the repo and couldn't seem to find a straightforward answer to this.

According to IPTC specifications, `ArtworkOrObject` is a bag of `ArtworkOrObjectDetails` structs. Some of those details e.g. `AOContentDescription` or `AOCreator` are arrays of information within the `ArtworkOrObjectDetails` struct. What is the best way to go about setting the value of a struct field to a `Bag` or `AltLang` or inserting array items into the value portion of a struct field?

**Comment by maupadhyay** [comment]
Hi @jwsinner ,

This sample https://github.com/adobe/XMP-Toolkit-SDK/blob/e0955b272ab6035b2921fa2c649aca5ecfe5ab81/samples/source/CustomSchema.cpp might be useful to you.
