### ISSUE TITLE
CopyXMP data changes XMP tag names 

### ISSUE THREAD

**Issue by LidiaMirkin** [adobe/XMP-Toolkit-SDK#61]
Hello 

We use XMP Toolkit to copy xmp related data from file to file.
for some reason, _1_ prefix is added to most of xmp tags in the result file.
Can you please advice ?

Thank you,
Lidia.

For example, 
Xmp.crs.Version becomes Xmp.crs_1_.Version

### Expected Behaviour
XMP tags are copied as is

### Actual Behaviour
_1_  is added to most of xmp tags in the result file

### steps to reproduce:
run sample code with attached file.
extract xmp data and compare
![hires](https://user-images.githubusercontent.com/45731239/168461435-2583058a-e1e5-4ab5-b0cb-5ad8420b482e.jpg)

#### Platform and Version
Windows/MAC

#### Sample Code that illustrates the problem

bool main()
{

string inFilename = "hires.jpg";
string outFilename = "before_xmp.jpg";

XMPMetaData t;
SXMPFiles::Initialize(options);

SXMPFiles myFile;
XMP_OptionBits opts = kXMPFiles_OpenForUpdate | kXMPFiles_OpenUseSmartHandler;

ok = myFile.OpenFile(inFilename, kXMP_UnknownFile, opts);
SXMPMeta meta;
if (ok)
{
	ok = myFile.GetXMP(&meta);
        XMP_OptionBits opts = kXMPFiles_OpenForUpdate | kXMPFiles_OpenUseSmartHandler;
	bool ok = myFile.OpenFile(outFilename, kXMP_UnknownFile, opts);
	if (!myFile.CanPutXMP(meta))
		return false;

	myFile.PutXMP(meta);
	myFile.CloseFile();
}

**Comment by maupadhyay** [comment]
Attached sample image has xmp packet which contains standard namespace prefix with different namespace URI.
While trying to create XMP object using this packet when already registered prefix is encounterd with some different namespace URI, a unique prefix is created from the encountered one.

For example sample image has namespace prefix crs with namescpace URI "http://photo-mate.com/xmp/". XMP already has this namespace registerd with different URI (see https://github.com/adobe/XMP-Toolkit-SDK/blob/main/XMPCore/source/XMPMeta.cpp#L818, https://github.com/adobe/XMP-Toolkit-SDK/blob/main/public/include/XMP_Const.h#L349). Hence crs is being changed to crs_1_ for uniqueness. That is why target image has changed XMP tag names.

This behaviour is as designed.
