### ISSUE TITLE
Understand this SDK

### ISSUE THREAD

**Issue by Tom3652** [adobe/XMP-Toolkit-SDK#68]
Hello ! 

I am sorry to make an issue for this but i had no idea where else to ask you about it.
I am an Android / Flutter dev and my client wants me to write XMP data (Yaw, Pitch, Roll, Focal etc) in the image EXIF (that i take from the Android camera API). 

I would like to understand how to proceed if i can use this SDK in my Android project for example, by compiling it from the `Gradle` , and also if this SDK is actually doing what i need to achieve ?
Can i call from some Java code the toolkit APIs if there are any ?

Thanks a lot in advance

**Comment by AMBE1203** [comment]
> Hello !
> 
> I am sorry to make an issue for this but i had no idea where else to ask you about it. I am an Android / Flutter dev and my client wants me to write XMP data (Yaw, Pitch, Roll, Focal etc) in the image EXIF (that i take from the Android camera API).
> 
> I would like to understand how to proceed if i can use this SDK in my Android project for example, by compiling it from the `Gradle` , and also if this SDK is actually doing what i need to achieve ? Can i call from some Java code the toolkit APIs if there are any ?
> 
> Thanks a lot in advance

have you integrated this sdk into your project please help me?

**Comment by AMBE1203** [comment]
> If the official Java version isn't working for you, you might consider trying https://github.com/Ashampoo/xmpcore.

Thanks for your help. i want to integrate sdk into my android application, is it possible?

**Comment by StefanOltmann** [comment]
> Thanks for your help. i want to integrate sdk into my android application, is it possible?

The official Java SDK as well as Ashampoo XMP Core both work with Android, yes. Use it like any other JVM library.

**Comment by maupadhyay** [comment]
XMP Java SDK source can be downloaded from https://www.adobe.com/devnet/xmp.html under _XMP Toolkit for Java_ section.
