### ISSUE TITLE
URL in "XMP-Toolkit-SDK/tools/cmake/ReadMe.txt" for Linux does not exist

### ISSUE THREAD

**Issue by ai2ys** [adobe/XMP-Toolkit-SDK#7]
The URL in Line 10 of file  "XMP-Toolkit-SDK/tools/cmake/ReadMe.txt" does not exist.
https://cmake.org/files/v3.15/cmake-3.15.5-Linux-i386.tar.gz

I used the following link instead:
https://cmake.org/files/v3.15/cmake-3.15.5-Linux-x86_64.tar.gz

**Comment by arpitapanda05** [comment]
Thank you for letting us know, we have updated the ReadMe.txt.
