### ISSUE TITLE
UTF-8 Issues

### ISSUE THREAD

**Issue by tester0077** [adobe/XMP-Toolkit-SDK#71]
Is this project still active??

I have serious doubts since the seems to at least one topic from more than 2 month ago which looks like some sort of SPAM and it has not been removed.

Still, I do have an issue with trying to get the correct string data from JPGs which have UTF-9 encode strings.

The seem to be some UTF-8 related option flag bits, but there seem to be no information one how they are expected to be used and what they are expected to do.

For now just a sign that there is any point in asking here would be a good start

**Comment by llothar** [comment]
Not sure if it is active. But it is still working. Some libraries can be used for 20 years almost untouched (like all the libpng image format libraries) and XMP is a format library. This is not the Javascript world.

Pretty sure you have problems when you have UTF-9 encoded strings.  

Build in debug mode, single step through the code and learn to understand it. For me the code feels very simple to understand.

**Comment by maupadhyay** [comment]
Hi @tester0077 
Can you please add more details about the issue you are facing.
