### ISSUE TITLE
XMP-Toolkit-SDK promoting vulnerable version 2.4.7 of libexpat?

### ISSUE THREAD

**Issue by hartwork** [adobe/XMP-Toolkit-SDK#73]
Hi!

It has come to my attention that in file [`third-party/expat/ReadMe.txt`](https://github.com/adobe/XMP-Toolkit-SDK/blob/main/third-party/expat/ReadMe.txt) XMP-Toolkit-SDK is promoting use of libexpat 2.4.7 while there is 2.5.0 by now [with security fixes](https://github.com/libexpat/libexpat/blob/master/expat/Changes). It would be great if you could update the file to promote either 2.5.0 or the "latest upstream version", instead. Thank you!

Best, Sebastian

**Comment by maupadhyay** [comment]
Fixed with July 2023 release

**Comment by hartwork** [comment]
Thanks!
