### ISSUE TITLE
How can we use Adobe's xmp image filter presets in our android app?

### ISSUE THREAD

**Issue by rajngarg** [adobe/XMP-Toolkit-SDK#9]

**Comment by InternetMaster1** [comment]
Any luck?

**Comment by pawankishorsingh** [comment]
Hi Ranjan

We could not understand what problem are you facing?
Can you please elaborate/explain more?

Regards
Pawan

**Comment by maupadhyay** [comment]
We have not heard back from Ranjan. Closing this issue.
